//! Auto-generated libfabric FFI bindings.
//!
//! Generated by bindgen from wrapper.h at build time.
//! This module is only compiled when EFA is available (libfabric found by build.rs).

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/libfabric_bindings.rs"));
